/**
 * species-images.js
 * Maps scientific name → Wikimedia Commons image URL for all species.
 * Used by the Species Explorer card renderer as a frontend-only overlay.
 * DO NOT modify the database or API.
 */
const SPECIES_IMAGES = {
  // ── AMPHIBIANS ──────────────────────────────────────────────────────────
  'Bufo bufo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Bufo_bufo_male_Luc_Viatour.jpg/320px-Bufo_bufo_male_Luc_Viatour.jpg',
  'Duttaphrynus melanostictus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Duttaphrynus_melanostictus_Tanintharyi.jpg/320px-Duttaphrynus_melanostictus_Tanintharyi.jpg',
  'Euphlyctis cyanophlyctis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Skittering_Frog_%28Euphlyctis_cyanophlyctis%29_by_Dr._Raju_Kasambe_DSCN1148_%2816%29.jpg/320px-Skittering_Frog_%28Euphlyctis_cyanophlyctis%29_by_Dr._Raju_Kasambe_DSCN1148_%2816%29.jpg',
  'Hoplobatrachus tigerinus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/HoplobatrachustigerinusD2.jpg/320px-HoplobatrachustigerinusD2.jpg',
  'Microhyla ornata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Microhyla_ornata.jpg/320px-Microhyla_ornata.jpg',
  'Nyctibatrachus major': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Nyctibatrachus_major.jpg/320px-Nyctibatrachus_major.jpg',
  'Ramanella montana': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Ramanella_Montana_DSCN3012.jpg/320px-Ramanella_Montana_DSCN3012.jpg',
  'Sphaerotheca breviceps': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Sphaerotheca_breviceps01.jpg/320px-Sphaerotheca_breviceps01.jpg',
  'Sphaerotheca dobsonii': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Sphaerotheca_breviceps01.jpg/320px-Sphaerotheca_breviceps01.jpg',
  'Uperodon globulosus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Ramanella_globulosa.jpg/320px-Ramanella_globulosa.jpg',

  // ── BIRDS ─────────────────────────────────────────────────────────────────
  'Acridotheres tristis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Common_myna2.jpg/320px-Common_myna2.jpg',
  'Alcedo atthis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Alcedo_atthis_-_Laertes.jpg/320px-Alcedo_atthis_-_Laertes.jpg',
  'Amaurornis phoenicurus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/White-breasted_Waterhen_%28Amaurornis_phoenicurus%29_in_Kolkata_I_IMG_0495.jpg/320px-White-breasted_Waterhen_%28Amaurornis_phoenicurus%29_in_Kolkata_I_IMG_0495.jpg',
  'Anastomus oscitans': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Asian_Open_billed_Stork_%28Anastomus_oscitans%29_in_Hyderabad_W_IMG_3898.jpg/320px-Asian_Open_billed_Stork_%28Anastomus_oscitans%29_in_Hyderabad_W_IMG_3898.jpg',
  'Anthracoceros coronatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Malabar_Pied_Hornbill_at_Yala.jpg/320px-Malabar_Pied_Hornbill_at_Yala.jpg',
  'Anthus hodgsoni': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Olive-backed_Pipit_%28Anthus_hodgsoni%29_in_Kolkata_W_IMG_3618.jpg/320px-Olive-backed_Pipit_%28Anthus_hodgsoni%29_in_Kolkata_W_IMG_3618.jpg',
  'Aquila rapax': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Aquila_rapax_2.jpg/320px-Aquila_rapax_2.jpg',
  'Ardea alba': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Ardea_alba_2006_bill.jpg/320px-Ardea_alba_2006_bill.jpg',
  'Ardea cinerea': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Ardea_cinerea_2.jpg/320px-Ardea_cinerea_2.jpg',
  'Ardeola grayii': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Indian_Pond_Heron_-_Ardeola_grayii_-_India_-_003.jpg/320px-Indian_Pond_Heron_-_Ardeola_grayii_-_India_-_003.jpg',
  'Bubulcus ibis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Cattle_Egret_-_natures_pics_edit.jpg/320px-Cattle_Egret_-_natures_pics_edit.jpg',
  'Bubo bubo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Eagle_Owl_Bubo_bubo.jpg/320px-Eagle_Owl_Bubo_bubo.jpg',
  'Butastur teesa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/White-eyed_Buzzard_%28Butastur_teesa%29.jpg/320px-White-eyed_Buzzard_%28Butastur_teesa%29.jpg',
  'Buteo buteo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Common_buzzard_-_Buteo_buteo.jpg/320px-Common_buzzard_-_Buteo_buteo.jpg',
  'Calidris minuta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Calidris_minuta_little_stint_winter.jpg/320px-Calidris_minuta_little_stint_winter.jpg',
  'Charadrius dubius': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Little_ringed_plover_arp.jpg/320px-Little_ringed_plover_arp.jpg',
  'Ciconia ciconia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Ciconia_ciconia_-_01.jpg/320px-Ciconia_ciconia_-_01.jpg',
  'Circus aeruginosus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Circus_aeruginosus_-_01.jpg/320px-Circus_aeruginosus_-_01.jpg',
  'Coracias benghalensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Indian_Roller_%28Coracias_benghalensis%29_in_Kolkata_W_IMG_4123.jpg/320px-Indian_Roller_%28Coracias_benghalensis%29_in_Kolkata_W_IMG_4123.jpg',
  'Corvus macrorhynchos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Large-billed_Crow_-_Corvus_macrorhynchos.jpg/320px-Large-billed_Crow_-_Corvus_macrorhynchos.jpg',
  'Corvus splendens': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/House_Crow_Corvus_splendens_by_Dr._Raju_Kasambe_DSCN1099_%282%29.jpg/320px-House_Crow_Corvus_splendens_by_Dr._Raju_Kasambe_DSCN1099_%282%29.jpg',
  'Coturnix coturnix': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Coturnix_coturnix_00.jpg/320px-Coturnix_coturnix_00.jpg',
  'Cuculus canorus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Common-cuckoo.jpg/320px-Common-cuckoo.jpg',
  'Dendrocygna javanica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Lesser_Whistling-duck_-_Dendrocygna_javanica.jpg/320px-Lesser_Whistling-duck_-_Dendrocygna_javanica.jpg',
  'Dicrurus macrocercus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Black-drongo.jpg/320px-Black-drongo.jpg',
  'Dinopium benghalense': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Black-rumped_flameback_-_Dinopium_benghalense_-_Uttarakhand_%28cropped%29.jpg/320px-Black-rumped_flameback_-_Dinopium_benghalense_-_Uttarakhand_%28cropped%29.jpg',
  'Elanus caeruleus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Black-shouldered_Kite_Elanus_caeruleus_by_Dr_Raju_Kasambe_DSCN5730_%286%29.jpg/320px-Black-shouldered_Kite_Elanus_caeruleus_by_Dr_Raju_Kasambe_DSCN5730_%286%29.jpg',
  'Eudynamys scolopaceus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Asian_Koel_1.jpg/320px-Asian_Koel_1.jpg',
  'Falco tinnunculus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Falco_tinnunculus_male.jpg/320px-Falco_tinnunculus_male.jpg',
  'Francolinus pondicerianus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Francolinus_pondicerianus.jpg/320px-Francolinus_pondicerianus.jpg',
  'Fulica atra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Fulica_atra_-_Riserva_naturale_Naviglio.jpg/320px-Fulica_atra_-_Riserva_naturale_Naviglio.jpg',
  'Gallus gallus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Gallus_gallus_-_Phasianidae.jpg/320px-Gallus_gallus_-_Phasianidae.jpg',
  'Gyps bengalensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/White-rumped_Vulture_Gyps_bengalensis.jpg/320px-White-rumped_Vulture_Gyps_bengalensis.jpg',
  'Halcyon smyrnensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/White-throated_Kingfisher_Halcyon_smyrnensis_by_Dr._Raju_Kasambe_DSCN0124_10.jpg/320px-White-throated_Kingfisher_Halcyon_smyrnensis_by_Dr._Raju_Kasambe_DSCN0124_10.jpg',
  'Haliastur indus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Brahminy_kite_RWD2.jpg/320px-Brahminy_kite_RWD2.jpg',
  'Hieraaetus pennatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Aquila_pennata_%28Booted_eagle%29.jpg/320px-Aquila_pennata_%28Booted_eagle%29.jpg',
  'Hirundo rustica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Hirundo_rustica_NRM.jpg/320px-Hirundo_rustica_NRM.jpg',
  'Indicator xanthonotus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Honeyguide.jpg/320px-Honeyguide.jpg',
  'Lanius vittatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Bay-backed_Shrike_Lanius_vittatus.jpg/320px-Bay-backed_Shrike_Lanius_vittatus.jpg',
  'Leptoptilos dubius': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Leptoptilos_dubius_couple_at_Bharatpur_1.jpg/320px-Leptoptilos_dubius_couple_at_Bharatpur_1.jpg',
  'Lonchura punctulata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Scaly-breasted_Munia_or_Spotted_Munia_%28Lonchura_punctulata%29_in_Tirupur.jpg/320px-Scaly-breasted_Munia_or_Spotted_Munia_%28Lonchura_punctulata%29_in_Tirupur.jpg',
  'Merops orientalis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Merops_orientalis_-_India-2.jpg/320px-Merops_orientalis_-_India-2.jpg',
  'Milvus migrans': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Black-eared_Kite_in_Islamabad_by_Shehzad_Hameed.jpg/320px-Black-eared_Kite_in_Islamabad_by_Shehzad_Hameed.jpg',
  'Motacilla alba': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/White_wagtail_flaviissima_variation_1.jpg/320px-White_wagtail_flaviissima_variation_1.jpg',
  'Mycteria leucocephala': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Painted_stork_%28Mycteria_leucocephala%29_Rajasthan.jpg/320px-Painted_stork_%28Mycteria_leucocephala%29_Rajasthan.jpg',
  'Nectarinia asiatica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Purple_Sunbird_%28Nectarinia_asiatica%29_male_in_Hyderabad_W_IMG_1381.jpg/320px-Purple_Sunbird_%28Nectarinia_asiatica%29_male_in_Hyderabad_W_IMG_1381.jpg',
  'Neophron percnopterus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Egyptian_vulture_%28Neophron_percnopterus%29.jpg/320px-Egyptian_vulture_%28Neophron_percnopterus%29.jpg',
  'Nycticorax nycticorax': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Nycticorax_nycticorax_-Wakodahatchee_Wetlands%2C_Delray_Beach%2C_Florida%2C_USA-8.jpg/320px-Nycticorax_nycticorax_-Wakodahatchee_Wetlands%2C_Delray_Beach%2C_Florida%2C_USA-8.jpg',
  'Oriolus oriolus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Oriolus_oriolus_-_02.jpg/320px-Oriolus_oriolus_-_02.jpg',
  'Orthotomus sutorius': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Common_Tailorbird_by_N._A._Naseer.jpg/320px-Common_Tailorbird_by_N._A._Naseer.jpg',
  'Passer domesticus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Passer_domesticus_male_%2815%29.jpg/320px-Passer_domesticus_male_%2815%29.jpg',
  'Pavo cristatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Peacock_Plumage.jpg/320px-Peacock_Plumage.jpg',
  'Pelecanus philippensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Spot-billed_Pelican_I_IMG_9954.jpg/320px-Spot-billed_Pelican_I_IMG_9954.jpg',
  'Phalacrocorax carbo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Great-cormorant-at-lake-Ammer.jpg/320px-Great-cormorant-at-lake-Ammer.jpg',
  'Phoenicopterus roseus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flamingo_at_Kamfers_Dam.jpg/320px-Flamingo_at_Kamfers_Dam.jpg',
  'Platalea leucorodia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Eurasian_Spoonbill_%28Platalea_leucorodia%29.jpg/320px-Eurasian_Spoonbill_%28Platalea_leucorodia%29.jpg',
  'Ploceus philippinus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Baya_Weaver_-_Ploceus_philippinus.jpg/320px-Baya_Weaver_-_Ploceus_philippinus.jpg',
  'Pluvialis squatarola': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Pluvialis_squatarola_-_Black-bellied_Plover.jpg/320px-Pluvialis_squatarola_-_Black-bellied_Plover.jpg',
  'Porphyrio porphyrio': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Porphyrio_porphyrio_-_Ritch_Grisell.jpg/320px-Porphyrio_porphyrio_-_Ritch_Grisell.jpg',
  'Prinia socialis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Ashy_Prinia_%28Prinia_socialis%29_in_Kolkata_W_IMG_3597.jpg/320px-Ashy_Prinia_%28Prinia_socialis%29_in_Kolkata_W_IMG_3597.jpg',
  'Psittacula krameri': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Rose-ringed_Parakeet_male_%28Psittacula_krameri%29.jpg/320px-Rose-ringed_Parakeet_male_%28Psittacula_krameri%29.jpg',
  'Pycnonotus cafer': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Red-vented_bulbul_%28Pycnonotus_cafer%29_from_Kolkata_I_IMG_3796.jpg/320px-Red-vented_bulbul_%28Pycnonotus_cafer%29_from_Kolkata_I_IMG_3796.jpg',
  'Anas platyrhynchos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Anas_platyrhynchos_male_female_quadrat.jpg/320px-Anas_platyrhynchos_male_female_quadrat.jpg',
  'Streptopelia chinensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Spilopelia_chinensis_-_Spot-breasted_Dove.jpg/320px-Spilopelia_chinensis_-_Spot-breasted_Dove.jpg',
  'Streptopelia decaocto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Eurasian_Collared_Dove_%28Streptopelia_decaocto%29.jpg/320px-Eurasian_Collared_Dove_%28Streptopelia_decaocto%29.jpg',
  'Streptopelia senegalensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Laughing_Dove_RWD2.jpg/320px-Laughing_Dove_RWD2.jpg',
  'Sturnia malabarica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Chestnut-tailed_Starling_%28Sturnia_malabarica%29_in_Kolkata_W_IMG_0072.jpg/320px-Chestnut-tailed_Starling_%28Sturnia_malabarica%29_in_Kolkata_W_IMG_0072.jpg',
  'Sturnus roseus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Rosy_starling_male.jpg/320px-Rosy_starling_male.jpg',
  'Terpsiphone paradisi': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Asian_Paradise-flycatcher_%28Terpsiphone_paradisi%29_Male.jpg/320px-Asian_Paradise-flycatcher_%28Terpsiphone_paradisi%29_Male.jpg',
  'Threskiornis melanocephalus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Black-headed_Ibis_%28Threskiornis_melanocephalus%29_in_Kolkata_I_IMG_8072.jpg/320px-Black-headed_Ibis_%28Threskiornis_melanocephalus%29_in_Kolkata_I_IMG_8072.jpg',
  'Tringa hypoleucos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Common_Sandpiper_-_Actitis_hypoleucos.jpg/320px-Common_Sandpiper_-_Actitis_hypoleucos.jpg',
  'Turdoides caudatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Common_Babbler_I_IMG_7040.jpg/320px-Common_Babbler_I_IMG_7040.jpg',
  'Upupa epops': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Common_hoopoe.jpg/320px-Common_hoopoe.jpg',
  'Vanellus indicus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Red-wattled_lapwing_in_Virudhanagar_district_of_Tamil_Nadu.jpg/320px-Red-wattled_lapwing_in_Virudhanagar_district_of_Tamil_Nadu.jpg',
  'Columba livia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Rock_dove_Columba_livia.jpg/320px-Rock_dove_Columba_livia.jpg',
  'Circus melanoleucos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Pied_Harrier.jpg/320px-Pied_Harrier.jpg',
  'Hieraaetus fasciatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Bonelli%27s_eagle_%28Hieraaetus_fasciatus%29.jpg/320px-Bonelli%27s_eagle_%28Hieraaetus_fasciatus%29.jpg',
  'Haliaeetus leucogaster': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/White-bellied_sea_eagle_-_Airlie_Beach.jpg/320px-White-bellied_sea_eagle_-_Airlie_Beach.jpg',

  // ── BUTTERFLIES ────────────────────────────────────────────────────────────
  'Papilio polytes': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Common_Mormon_Papilio_polytes_by_Dr_Raju_Kasambe_DSCN7578_%284%29.jpg/320px-Common_Mormon_Papilio_polytes_by_Dr_Raju_Kasambe_DSCN7578_%284%29.jpg',
  'Papilio hector': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Crimson_Rose_Atrophaneura_hector.jpg/320px-Crimson_Rose_Atrophaneura_hector.jpg',
  'Atrophaneura aristolochiae': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Common_Rose_%28Atrophaneura_aristolochiae%29_by_Dr._Raju_Kasambe_DSCN8867_%286%29.jpg/320px-Common_Rose_%28Atrophaneura_aristolochiae%29_by_Dr._Raju_Kasambe_DSCN8867_%286%29.jpg',
  'Papilio buddha': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Malabar_banded_peacock_%28Papilio_buddha%29_male_Thekkady.jpg/320px-Malabar_banded_peacock_%28Papilio_buddha%29_male_Thekkady.jpg',
  'Papilio demoleus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Lime_Butterfly_%28Papilio_demoleus%29_male_mudpuddling_in_Kolkata_I_IMG_3658.jpg/320px-Lime_Butterfly_%28Papilio_demoleus%29_male_mudpuddling_in_Kolkata_I_IMG_3658.jpg',
  'Graphium sarpedon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Common_Bluebottle_Graphium_sarpedon.jpg/320px-Common_Bluebottle_Graphium_sarpedon.jpg',
  'Troides minos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Southern_Birdwing_%28Troides_minos%29_UP.jpg/320px-Southern_Birdwing_%28Troides_minos%29_UP.jpg',
  'Catopsilia pomona': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Common_Emigrant_Catopsilia_pomona_mating_by_Dr._Raju_Kasambe_DSCN7738_%284%29.jpg/320px-Common_Emigrant_Catopsilia_pomona_mating_by_Dr._Raju_Kasambe_DSCN7738_%284%29.jpg',
  'Catopsilia pyranthe': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Mottled_Emigrant_%28Catopsilia_pyranthe%29_-_male.jpg/320px-Mottled_Emigrant_%28Catopsilia_pyranthe%29_-_male.jpg',
  'Eurema hecabe': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Common_Grass_Yellow_%28Eurema_hecabe%29_at_Kolkata_I_IMG_4803.jpg/320px-Common_Grass_Yellow_%28Eurema_hecabe%29_at_Kolkata_I_IMG_4803.jpg',
  'Delias eucharis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Jezebel_Butterfly_%28Delias_eucharis%29_by_Dr._Raju_Kasambe_DSCN1088_%286%29.jpg/320px-Jezebel_Butterfly_%28Delias_eucharis%29_by_Dr._Raju_Kasambe_DSCN1088_%286%29.jpg',
  'Appias libythea': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Stripped_Albatross_Appias_libythea.jpg/320px-Stripped_Albatross_Appias_libythea.jpg',
  'Danaus chrysippus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Danaus_chrysippus_male_%28Plain_Tiger%29.jpg/320px-Danaus_chrysippus_male_%28Plain_Tiger%29.jpg',
  'Danaus genutia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Danaus_genutia_%28Striped_Tiger%29_in_Hyderabad%2C_India.jpg/320px-Danaus_genutia_%28Striped_Tiger%29_in_Hyderabad%2C_India.jpg',
  'Tirumala limniace': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Blue_tiger_%28Tirumala_limniace%29.jpg/320px-Blue_tiger_%28Tirumala_limniace%29.jpg',
  'Euploea core': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Common_crow_%28Euploea_core%29_in_Hyderabad%2C_India.jpg/320px-Common_crow_%28Euploea_core%29_in_Hyderabad%2C_India.jpg',
  'Ideopsis similis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Ideopsis_similis.jpg/320px-Ideopsis_similis.jpg',
  'Hypolimnas bolina': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Hypolimnas_bolina_-Kadavoor-2016-08-01-001.jpg/320px-Hypolimnas_bolina_-Kadavoor-2016-08-01-001.jpg',
  'Hypolimnas misippus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Danaid_Eggfly_Hypolimnas_misippus_Female_by_Dr._Raju_Kasambe_DSCN0055_%287%29.jpg/320px-Danaid_Eggfly_Hypolimnas_misippus_Female_by_Dr._Raju_Kasambe_DSCN0055_%287%29.jpg',
  'Junonia almana': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Peacock_Pansy_%28Junonia_almana%29-_male_in_Kolkata_I_IMG_2720.jpg/320px-Peacock_Pansy_%28Junonia_almana%29-_male_in_Kolkata_I_IMG_2720.jpg',
  'Junonia atlites': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Grey_Pansy_%28Junonia_atlites%29_in_Hyderabad.jpg/320px-Grey_Pansy_%28Junonia_atlites%29_in_Hyderabad.jpg',
  'Junonia hierta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Yellow_Pansy_%28Junonia_hierta%29_at_Kolkata_I_IMG_9083.jpg/320px-Yellow_Pansy_%28Junonia_hierta%29_at_Kolkata_I_IMG_9083.jpg',
  'Junonia iphita': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Chocolate_Pansy_%28Junonia_iphita%29_at_Hyderabad.jpg/320px-Chocolate_Pansy_%28Junonia_iphita%29_at_Hyderabad.jpg',
  'Junonia lemonias': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Lemon_pansy_%28Junonia_lemonias%29_W_by_Dr._Raju_Kasambe_DSCN7534_%283%29.jpg/320px-Lemon_pansy_%28Junonia_lemonias%29_W_by_Dr._Raju_Kasambe_DSCN7534_%283%29.jpg',
  'Melanitis leda': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Common_Evening_Brown_%28Melanitis_leda%29_W_by_Dr._Raju_Kasambe_DSCN4620_%2814%29.jpg/320px-Common_Evening_Brown_%28Melanitis_leda%29_W_by_Dr._Raju_Kasambe_DSCN4620_%2814%29.jpg',
  'Ypthima baldus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Common_fivering_Ypthima_baldus_Kadavoor.jpg/320px-Common_fivering_Ypthima_baldus_Kadavoor.jpg',
  'Ariadne ariadne': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Ariadne_ariadne_by_kadavoor.jpg/320px-Ariadne_ariadne_by_kadavoor.jpg',
  'Neptis hylas': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Common_Sailer_%28Neptis_hylas%29_at_Nungambakkam_I2_IMG_5516.jpg/320px-Common_Sailer_%28Neptis_hylas%29_at_Nungambakkam_I2_IMG_5516.jpg',
  'Euthalia aconthea': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Baron_%28Euthalia_aconthea%29.jpg/320px-Baron_%28Euthalia_aconthea%29.jpg',
  'Charaxes bharata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Charaxes_bharata-01.jpg/320px-Charaxes_bharata-01.jpg',
  'Nacaduba beroe': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Pale_Cerulean_%28Jamides_celeno%29_at_Hyderabad.jpg/320px-Pale_Cerulean_%28Jamides_celeno%29_at_Hyderabad.jpg',
  'Jamides celeno': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Pale_Cerulean_%28Jamides_celeno%29_at_Hyderabad.jpg/320px-Pale_Cerulean_%28Jamides_celeno%29_at_Hyderabad.jpg',
  'Chilades laius': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Lime_Blue_%28Chilades_laius%29_by_Dr._Raju_Kasambe_DSCN4476_%284%29.jpg/320px-Lime_Blue_%28Chilades_laius%29_by_Dr._Raju_Kasambe_DSCN4476_%284%29.jpg',
  'Zizeeria karsandra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Dark_Grass_Blue_Zizeeria_karsandra.jpg/320px-Dark_Grass_Blue_Zizeeria_karsandra.jpg',
  'Euchrysops cnejus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Gram_Blue_%28Euchrysops_cnejus%29_- Kadavoor.jpg/320px-Gram_Blue_%28Euchrysops_cnejus%29_-_Kadavoor.jpg',
  'Catochrysops strabo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Forget-me-not_%28Catochrysops_strabo%29_male_at_Hyderabad.jpg/320px-Forget-me-not_%28Catochrysops_strabo%29_male_at_Hyderabad.jpg',
  'Spalgis epeus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Apefly_%28Spalgis_epeus%29.jpg/320px-Apefly_%28Spalgis_epeus%29.jpg',
  'Castalius rosimon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Common_Pierrot_%28Castalius_rosimon%29.jpg/320px-Common_Pierrot_%28Castalius_rosimon%29.jpg',
  'Talicada nyseus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Red_Pierrot_%28Talicada_nyseus%29_by_Dr._Raju_Kasambe_DSCN8598_%2822%29.jpg/320px-Red_Pierrot_%28Talicada_nyseus%29_by_Dr._Raju_Kasambe_DSCN8598_%2822%29.jpg',
  'Papilio memnon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Great_Mormon_%28Papilio_memnon%29.jpg/320px-Great_Mormon_%28Papilio_memnon%29.jpg',
  'Papilio paris': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Blue_Mormon_Papilio_polymnestor.jpg/320px-Blue_Mormon_Papilio_polymnestor.jpg',
  'Papilio polymnestor': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Blue_Mormon_Papilio_polymnestor.jpg/320px-Blue_Mormon_Papilio_polymnestor.jpg',

  // ── DRAGONFLIES ────────────────────────────────────────────────────────────
  'Brachythemis contaminata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Brachythemis_contaminata_male.jpg/320px-Brachythemis_contaminata_male.jpg',
  'Crocothemis servilia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Crocothemis_servilia_mating.jpg/320px-Crocothemis_servilia_mating.jpg',
  'Diplacodes trivialis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Diplacodes_trivialis.jpg/320px-Diplacodes_trivialis.jpg',
  'Neurothemis fluctuans': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Neurothemis_fluctuans-_male-_Kerala.jpg/320px-Neurothemis_fluctuans-_male-_Kerala.jpg',
  'Orthetrum sabina': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Orthetrum_sabina_-_male.jpg/320px-Orthetrum_sabina_-_male.jpg',
  'Pantala flavescens': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Wandering_Glider_01.jpg/320px-Wandering_Glider_01.jpg',
  'Rhodothemis rufa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Rhodothemis_rufa_male_%28Kadavoor%29.jpg/320px-Rhodothemis_rufa_male_%28Kadavoor%29.jpg',
  'Trithemis aurora': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Trithemis_aurora_%28male%29_Kadavoor.jpg/320px-Trithemis_aurora_%28male%29_Kadavoor.jpg',
  'Trithemis festiva': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Trithemis_festiva_male_0.3.jpg/320px-Trithemis_festiva_male_0.3.jpg',
  'Ischnura senegalensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Ischnura_senegalensis_mating.jpg/320px-Ischnura_senegalensis_mating.jpg',
  'Ceriagrion coromandelianum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Ceriagrion_coromandelianum_female.jpg/320px-Ceriagrion_coromandelianum_female.jpg',
  'Agriocnemis pygmaea': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Agriocnemis_pygmaea_-_male.jpg/320px-Agriocnemis_pygmaea_-_male.jpg',
  'Pseudagrion microcephalum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Pseudagrion_microcephalum-_male_at_Kadavoor.jpg/320px-Pseudagrion_microcephalum-_male_at_Kadavoor.jpg',

  // ── FISH ───────────────────────────────────────────────────────────────────
  'Catla catla': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Catla_catla.jpg/320px-Catla_catla.jpg',
  'Channa striata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Channa_striata_Striped_Snakehead.jpg/320px-Channa_striata_Striped_Snakehead.jpg',
  'Cirrhinus cirrhosus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Cirrhinus_cirrhosus.jpg/320px-Cirrhinus_cirrhosus.jpg',
  'Clarias batrachus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Clarias-batrachus.jpg/320px-Clarias-batrachus.jpg',
  'Cyprinus carpio': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Common_carp.jpg/320px-Common_carp.jpg',
  'Gambusia affinis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Gambusia_affinis.jpg/320px-Gambusia_affinis.jpg',
  'Labeo rohita': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Labeo_rohita.jpg/320px-Labeo_rohita.jpg',
  'Mastacembelus armatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Mastacembelus_armatus.jpg/320px-Mastacembelus_armatus.jpg',
  'Mystus tengara': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Mystus_tengara.jpg/320px-Mystus_tengara.jpg',
  'Oreochromis niloticus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Nile_tilapia_%28Oreochromis_niloticus%29.jpg/320px-Nile_tilapia_%28Oreochromis_niloticus%29.jpg',
  'Pethia conchonius': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Rosy_Barb.jpg/320px-Rosy_Barb.jpg',
  'Rasbora daniconius': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Rasbora_daniconius.jpg/320px-Rasbora_daniconius.jpg',
  'Rita rita': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Rita_rita.jpg/320px-Rita_rita.jpg',
  'Tor khudree': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Tor_khudree.jpg/320px-Tor_khudree.jpg',
  'Tor tor': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Tor_khudree.jpg/320px-Tor_khudree.jpg',
  'Wallago attu': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Wallago_attu.jpg/320px-Wallago_attu.jpg',
  'Xenentodon cancila': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Xenentodon_cancila.jpg/320px-Xenentodon_cancila.jpg',

  // ── INSECTS ────────────────────────────────────────────────────────────────
  'Apis dorsata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Apis_dorsata_hive.jpg/320px-Apis_dorsata_hive.jpg',
  'Apis florea': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Apis_florea_worker.jpg/320px-Apis_florea_worker.jpg',
  'Gryllus bimaculatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Field_cricket_%28Gryllus_bimaculatus%29.jpg/320px-Field_cricket_%28Gryllus_bimaculatus%29.jpg',
  'Mantis religiosa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Mantis_religiosa_01%28viki%29.jpg/320px-Mantis_religiosa_01%28viki%29.jpg',
  'Bombyx mori': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Silkworm_cocoon.jpg/320px-Silkworm_cocoon.jpg',
  'Sympetrum striolatum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Sympetrum_striolatum_-_side_%28aka%29.jpg/320px-Sympetrum_striolatum_-_side_%28aka%29.jpg',
  'Hierodula membranacea': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Hierodula_membranacea.jpg/320px-Hierodula_membranacea.jpg',
  'Locusta migratoria': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Locusta_migratoria.jpg/320px-Locusta_migratoria.jpg',
  'Coccinella septempunctata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Coccinella_septempunctata.jpg/320px-Coccinella_septempunctata.jpg',
  'Periplaneta americana': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Periplaneta_americana.jpg/320px-Periplaneta_americana.jpg',
  'Vespa tropica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Vespa_tropica.jpg/320px-Vespa_tropica.jpg',
  'Oecophylla smaragdina': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Oecophylla_smaragdina_in_West_Bengal.jpg/320px-Oecophylla_smaragdina_in_West_Bengal.jpg',

  // ── MAMMALS ────────────────────────────────────────────────────────────────
  'Antilope cervicapra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Antilope_cervicapra_%28Panna%29.jpg/320px-Antilope_cervicapra_%28Panna%29.jpg',
  'Canis aureus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Golden_Jackal_Canis_aureus_by_Dr._Raju_Kasambe_DSC_0145_%287%29.jpg/320px-Golden_Jackal_Canis_aureus_by_Dr._Raju_Kasambe_DSC_0145_%287%29.jpg',
  'Canis lupus pallipes': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Indian_Wolf_%28Canis_lupus_pallipes%29.jpg/320px-Indian_Wolf_%28Canis_lupus_pallipes%29.jpg',
  'Cervus unicolor': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Sambar_deers_in_Bandipur.jpg/320px-Sambar_deers_in_Bandipur.jpg',
  'Cuon alpinus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Cuon_alpinus_in_Kaziranga.jpg/320px-Cuon_alpinus_in_Kaziranga.jpg',
  'Cynopterus sphinx': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Short-nosed_Fruit_Bat.jpg/320px-Short-nosed_Fruit_Bat.jpg',
  'Felis chaus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Felis_chaus.jpg/320px-Felis_chaus.jpg',
  'Funambulus palmarum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Funambulus_palmarum_in_Kolkata.jpg/320px-Funambulus_palmarum_in_Kolkata.jpg',
  'Gazella bennettii': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Indian_gazelle_at_Velavadar.jpg/320px-Indian_gazelle_at_Velavadar.jpg',
  'Herpestes edwardsii': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Indian_Grey_Mongoose_%28Herpestes_edwardsii%29.jpg/320px-Indian_Grey_Mongoose_%28Herpestes_edwardsii%29.jpg',
  'Herpestes smithii': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Herpestes_smithii.jpg/320px-Herpestes_smithii.jpg',
  'Hyaena hyaena': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Hyena.jpg/320px-Hyena.jpg',
  'Lepus nigricollis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Indian_Hare_%28Lepus_nigricollis%29_in_Kutch.jpg/320px-Indian_Hare_%28Lepus_nigricollis%29_in_Kutch.jpg',
  'Lutrogale perspicillata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Smooth-coated_Otter_Lutrogale_perspicillata_by_Dr_Raju_Kasambe_DSC_1015_%286%29.jpg/320px-Smooth-coated_Otter_Lutrogale_perspicillata_by_Dr_Raju_Kasambe_DSC_1015_%286%29.jpg',
  'Macaca mulatta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Macaca_mulatta_-_Noida.jpg/320px-Macaca_mulatta_-_Noida.jpg',
  'Manis crassicaudata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Pangolin_India.jpg/320px-Pangolin_India.jpg',
  'Melursus ursinus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Sloth_Bear_Melursus_ursinus_by_Dharani_Prakash.jpg/320px-Sloth_Bear_Melursus_ursinus_by_Dharani_Prakash.jpg',
  'Millardia gleadowi': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Sand-coloured_Soft-furred_Rat.jpg/320px-Sand-coloured_Soft-furred_Rat.jpg',
  'Bandicota bengalensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Bandicota_bengalensis.jpg/320px-Bandicota_bengalensis.jpg',
  'Paradoxurus hermaphroditus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Asian_Palm_Civet_Paradoxurus_hermaphroditus.jpg/320px-Asian_Palm_Civet_Paradoxurus_hermaphroditus.jpg',
  'Panthera pardus fusca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Indian_Leopard_Jhalana.jpg/320px-Indian_Leopard_Jhalana.jpg',
  'Paraechinus micropus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Indian_hedgehog.jpg/320px-Indian_hedgehog.jpg',
  'Pipistrellus coromandra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Pipistrellus_coromandra.jpg/320px-Pipistrellus_coromandra.jpg',
  'Prionailurus rubiginosus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Prionailurus_rubiginosus-Kanha.jpg/320px-Prionailurus_rubiginosus-Kanha.jpg',
  'Rusa unicolor': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Sambar_deers_in_Bandipur.jpg/320px-Sambar_deers_in_Bandipur.jpg',
  'Sus scrofa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Wild_Boar_Sus_Scrofa.jpg/320px-Wild_Boar_Sus_Scrofa.jpg',
  'Viverricula indica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Viverricula_indica.jpg/320px-Viverricula_indica.jpg',
  'Vulpes bengalensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Indian_Fox.jpg/320px-Indian_Fox.jpg',
  'Boselaphus tragocamelus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Nilgai_Boselaphus_tragocamelus_by_Dr_Raju_Kasambe_DSC00181_%286%29.jpg/320px-Nilgai_Boselaphus_tragocamelus_by_Dr_Raju_Kasambe_DSC00181_%286%29.jpg',

  // ── REPTILES ───────────────────────────────────────────────────────────────
  'Ahaetulla nasuta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Common_Vine_Snake.jpg/320px-Common_Vine_Snake.jpg',
  'Amphiesma stolatum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Buff_Striped_Keelback_Amphiesma_stolatum_by_Dr._Raju_Kasambe_DSCN2683_%282%29.jpg/320px-Buff_Striped_Keelback_Amphiesma_stolatum_by_Dr._Raju_Kasambe_DSCN2683_%282%29.jpg',
  'Boiga trigonata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Indian_Cat_Snake_%28Boiga_trigonata%29.jpg/320px-Indian_Cat_Snake_%28Boiga_trigonata%29.jpg',
  'Bungarus caeruleus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Indian_Krait_-_Common_Krait_Bungarus_caeruleus_by_Dr._Raju_Kasambe_DSC_2664_%281%29.jpg/320px-Indian_Krait_-_Common_Krait_Bungarus_caeruleus_by_Dr._Raju_Kasambe_DSC_2664_%281%29.jpg',
  'Calotes versicolor': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Calotes_versicolor_%28Agamidae%29.jpg/320px-Calotes_versicolor_%28Agamidae%29.jpg',
  'Cerberus rynchops': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Dog-faced_Water_Snake_%28Cerberus_rynchops%29.jpg/320px-Dog-faced_Water_Snake_%28Cerberus_rynchops%29.jpg',
  'Chamaeleo zeylanicus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Indian_Chameleon_%28Chamaeleo_zeylanicus%29.jpg/320px-Indian_Chameleon_%28Chamaeleo_zeylanicus%29.jpg',
  'Crocodylus palustris': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Mugger_Crocodile_%28Crocodylus_palustris%29.jpg/320px-Mugger_Crocodile_%28Crocodylus_palustris%29.jpg',
  'Daboia russelii': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/DaboiaRusseli_andBaby.jpg/320px-DaboiaRusseli_andBaby.jpg',
  'Dendrelaphis tristis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Dendrelaphis_tristis.jpg/320px-Dendrelaphis_tristis.jpg',
  'Echis carinatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Echis_carinatus_in_Coimbatore.jpg/320px-Echis_carinatus_in_Coimbatore.jpg',
  'Eryx conicus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Common_Sand_Boa_Eryx_conicus.jpg/320px-Common_Sand_Boa_Eryx_conicus.jpg',
  'Eryx johnii': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Eryx_johnii.jpg/320px-Eryx_johnii.jpg',
  'Eutropis carinata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eutropis_carinata.jpg/320px-Eutropis_carinata.jpg',
  'Eutropis macularia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Eutropis_macularia_at_Kolkata.jpg/320px-Eutropis_macularia_at_Kolkata.jpg',
  'Fowlea piscator': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Fowlea_piscator_by_Dr._Raju_Kasambe_DSCN0290_%282%29.jpg/320px-Fowlea_piscator_by_Dr._Raju_Kasambe_DSCN0290_%282%29.jpg',
  'Geochelone elegans': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Geochelone_elegans.jpg/320px-Geochelone_elegans.jpg',
  'Hemidactylus frenatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Hemidactylus_frenatus_-_Common_house_gecko.jpg/320px-Hemidactylus_frenatus_-_Common_house_gecko.jpg',
  'Hemidactylus triedrus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Hemidactylus_triedrus.jpg/320px-Hemidactylus_triedrus.jpg',
  'Lissemys punctata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Lissemys_punctata.jpg/320px-Lissemys_punctata.jpg',
  'Lycodon aulicus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Common_Wolf_Snake_%28Lycodon_aulicus%29.jpg/320px-Common_Wolf_Snake_%28Lycodon_aulicus%29.jpg',
  'Lycodon striatus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Lycodon_striatus.jpg/320px-Lycodon_striatus.jpg',
  'Naja naja': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Spectacled_Cobra.jpg/320px-Spectacled_Cobra.jpg',
  'Nilssonia gangetica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Nilssonia_gangetica.jpg/320px-Nilssonia_gangetica.jpg',
  'Pangshura tecta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Pangshura_tecta.jpg/320px-Pangshura_tecta.jpg',
  'Psammophilus dorsalis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Psammophilus_dorsalis.jpg/320px-Psammophilus_dorsalis.jpg',
  'Ptyas mucosa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Indian_Rat_Snake_Ptyas_mucosa.jpg/320px-Indian_Rat_Snake_Ptyas_mucosa.jpg',
  'Python molurus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Python_molurus_molurus_2.jpg/320px-Python_molurus_molurus_2.jpg',
  'Sitana ponticeriana': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Fan-throated_Lizard_%28Sitana_ponticeriana%29.jpg/320px-Fan-throated_Lizard_%28Sitana_ponticeriana%29.jpg',
  'Varanus bengalensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Varanus_bengalensis.jpg/320px-Varanus_bengalensis.jpg',
  'Coelognathus helena': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Coelognathus_helena.jpg/320px-Coelognathus_helena.jpg',
  'Coelognathus helena monticollaris': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Coelognathus_helena.jpg/320px-Coelognathus_helena.jpg',
  'Dendrelaphis pictus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Dendrelaphis_pictus_%28Painted_Bronzeback%29.jpg/320px-Dendrelaphis_pictus_%28Painted_Bronzeback%29.jpg',
  'Psammophilus blanfordanus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Psammophilus_dorsalis.jpg/320px-Psammophilus_dorsalis.jpg',
  'Atretium schistosum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Atretium_schistosum.jpg/320px-Atretium_schistosum.jpg',

  // ── MEDICINAL PLANTS ─────────────────────────────────────────────────────
  'Withania somnifera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Withania_somnifera_fruit.jpg/320px-Withania_somnifera_fruit.jpg',
  'Ocimum tenuiflorum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Ocimum_tenuiflorum3.jpg/320px-Ocimum_tenuiflorum3.jpg',
  'Azadirachta indica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Azadirachta_indica_-_Neem.jpg/320px-Azadirachta_indica_-_Neem.jpg',
  'Curcuma longa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Curcuma_longa_roots.jpg/320px-Curcuma_longa_roots.jpg',
  'Tinospora cordifolia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Tinospora_cordifolia.jpg/320px-Tinospora_cordifolia.jpg',
  'Bacopa monnieri': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Bacopa_monnieri1.jpg/320px-Bacopa_monnieri1.jpg',
  'Terminalia chebula': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Terminalia_chebula.jpg/320px-Terminalia_chebula.jpg',
  'Terminalia bellirica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Terminalia_bellirica.jpg/320px-Terminalia_bellirica.jpg',
  'Phyllanthus emblica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Phyllanthus_emblica.jpg/320px-Phyllanthus_emblica.jpg',
  'Asparagus racemosus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Asparagus_racemosus.jpg/320px-Asparagus_racemosus.jpg',
  'Glycyrrhiza glabra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Glycyrrhiza_glabra.jpg/320px-Glycyrrhiza_glabra.jpg',
  'Rauvolfia serpentina': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Rauwolfia_serpentina.jpg/320px-Rauwolfia_serpentina.jpg',
  'Aloe vera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Aloe_vera_flower_inset.png/320px-Aloe_vera_flower_inset.png',
  'Catharanthus roseus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/CatharanthusRoseus1.jpg/320px-CatharanthusRoseus1.jpg',
  'Cassia fistula': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Cassia_fistula_flowers.jpg/320px-Cassia_fistula_flowers.jpg',
  'Terminalia arjuna': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Terminalia_arjuna.jpg/320px-Terminalia_arjuna.jpg',
  'Aegle marmelos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Bael_Fruits.jpg/320px-Bael_Fruits.jpg',
  'Andrographis paniculata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Andrographis_paniculata.jpg/320px-Andrographis_paniculata.jpg',
  'Boswellia serrata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Boswellia_serrata.jpg/320px-Boswellia_serrata.jpg',
  'Calotropis procera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Calotropis_procera_flowers.jpg/320px-Calotropis_procera_flowers.jpg',
  'Commiphora wightii': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Commiphora_wightii.jpg/320px-Commiphora_wightii.jpg',
  'Cynodon dactylon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Cynodon_dactylon.jpg/320px-Cynodon_dactylon.jpg',
  'Cyperus rotundus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Cyperus_rotundus.jpg/320px-Cyperus_rotundus.jpg',
  'Datura stramonium': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Datura_stramonium.jpg/320px-Datura_stramonium.jpg',
  'Gymnema sylvestre': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Gymnema_sylvestre.jpg/320px-Gymnema_sylvestre.jpg',
  'Justicia adhatoda': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Justicia_adhatoda.jpg/320px-Justicia_adhatoda.jpg',
  'Moringa oleifera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Moringa_oleifera.jpg/320px-Moringa_oleifera.jpg',
  'Nardostachys jatamansi': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Nardostachys_jatamansi.jpg/320px-Nardostachys_jatamansi.jpg',
  'Picrorhiza kurroa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Picrorhiza_kurrooa.jpg/320px-Picrorhiza_kurrooa.jpg',
  'Trigonella foenum-graecum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Trigonella_foenum_graecum.jpg/320px-Trigonella_foenum_graecum.jpg',
  'Zingiber officinale': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Zingiber_officinale_-_Köhler–s_Medizinal-Pflanzen-139.jpg/320px-Zingiber_officinale_-_Köhler–s_Medizinal-Pflanzen-139.jpg',

  // ── TREES ──────────────────────────────────────────────────────────────────
  'Ficus benghalensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Ficus_benghalensis_-_Howrah_2011-07-28_4165.jpg/320px-Ficus_benghalensis_-_Howrah_2011-07-28_4165.jpg',
  'Ficus religiosa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Ficus_religiosa_bo.jpg/320px-Ficus_religiosa_bo.jpg',
  'Mangifera indica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Mangifera_indica_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-087.jpg/320px-Mangifera_indica_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-087.jpg',
  'Tectona grandis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Tectona_grandis_Lf.jpg/320px-Tectona_grandis_Lf.jpg',
  'Dalbergia sissoo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Dalbergia_sissoo.jpg/320px-Dalbergia_sissoo.jpg',
  'Shorea robusta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Shorea_robusta.jpg/320px-Shorea_robusta.jpg',
  'Tamarindus indica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Tamarind_paste_%26_pods.jpg/320px-Tamarind_paste_%26_pods.jpg',
  'Butea monosperma': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Butea_monosperma_in_flower.jpg/320px-Butea_monosperma_in_flower.jpg',
  'Delonix regia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Royal_Poinciana2.jpg/320px-Royal_Poinciana2.jpg',
  'Vachellia nilotica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Acacia_nilotica_var_tomentosa.jpg/320px-Acacia_nilotica_var_tomentosa.jpg',
  'Pongamia pinnata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Pongamia_pinnata.jpg/320px-Pongamia_pinnata.jpg',
  'Syzygium cumini': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Syzygium_cumini_in_Kolkata_W_IMG_3971.jpg/320px-Syzygium_cumini_in_Kolkata_W_IMG_3971.jpg',
  'Bambusa bambos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Bamboos_in_the_forest.jpg/320px-Bamboos_in_the_forest.jpg',
  'Madhuca longifolia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Mahua.jpg/320px-Mahua.jpg',
  'Ficus racemosa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Ficus_racemosa.jpg/320px-Ficus_racemosa.jpg',
  'Cocos nucifera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Coconut_palm_on_the_beach.jpg/320px-Coconut_palm_on_the_beach.jpg',
  'Psidium guajava': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Guava_ID.jpg/320px-Guava_ID.jpg',
  'Artocarpus heterophyllus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Jackfruit_Artocarpus_heterophyllus.jpg/320px-Jackfruit_Artocarpus_heterophyllus.jpg',
  'Leucaena leucocephala': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Leucaena_leucocephala.jpg/320px-Leucaena_leucocephala.jpg',
  'Dalbergia latifolia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Dalbergia_latifolia.jpg/320px-Dalbergia_latifolia.jpg',
  'Saraca asoca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Saraca_asoka.jpg/320px-Saraca_asoka.jpg',
  'Bombax ceiba': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Bombax_ceiba_in_bloom.jpg/320px-Bombax_ceiba_in_bloom.jpg',
  'Erythrina variegata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Erythrina_variegata.jpg/320px-Erythrina_variegata.jpg',
  'Terminalia elliptica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Terminalia_elliptica_Willd.jpg/320px-Terminalia_elliptica_Willd.jpg',
  'Magnolia champaca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Magnolia_champaca.jpg/320px-Magnolia_champaca.jpg',
  'Borassus flabellifer': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Borassus_flabellifer.jpg/320px-Borassus_flabellifer.jpg',
  'Plumeria alba': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Plumeria_alba.jpg/320px-Plumeria_alba.jpg',
  'Neolamarckia cadamba': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Neolamarckia_cadamba.jpg/320px-Neolamarckia_cadamba.jpg',
  'Phoenix sylvestris': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Phoenix_sylvestris.jpg/320px-Phoenix_sylvestris.jpg',
  'Moringa oleifera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Moringa_oleifera.jpg/320px-Moringa_oleifera.jpg',
  'Peltophorum pterocarpum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Peltophorum_pterocarpum.jpg/320px-Peltophorum_pterocarpum.jpg',
  'Annona squamosa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Annona_squamosa.jpg/320px-Annona_squamosa.jpg',
  'Manilkara zapota': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/ManilkaraZapotaFruit.jpg/320px-ManilkaraZapotaFruit.jpg',
  'Salix tetrasperma': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Salix_tetrasperma.jpg/320px-Salix_tetrasperma.jpg',
  'Terminalia catappa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Terminalia_catappa.jpg/320px-Terminalia_catappa.jpg',
  'Murraya koenigii': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Murraya_koenigii.jpg/320px-Murraya_koenigii.jpg',
  'Ficus carica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ficus_carica.jpg/320px-Ficus_carica.jpg',
  'Ficus elastica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Ficus_elastica_-_Rubber_Fig_-_Kerala.jpg/320px-Ficus_elastica_-_Rubber_Fig_-_Kerala.jpg',
  'Punica granatum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Hapus_Mango.jpg/320px-Hapus_Mango.jpg',
  'Areca catechu': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Areca_catechu.jpg/320px-Areca_catechu.jpg',
  'Casuarina equisetifolia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Casuarina_equisetifolia.jpg/320px-Casuarina_equisetifolia.jpg',
  'Senegalia catechu': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Senegalia_catechu.jpg/320px-Senegalia_catechu.jpg',
  'Samanea saman': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Samanea_saman_-_Monkeypod_tree.jpg/320px-Samanea_saman_-_Monkeypod_tree.jpg',
  'Holoptelea integrifolia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Holoptelea_integrifolia.jpg/320px-Holoptelea_integrifolia.jpg',
  'Hyophorbe lagenicaulis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Hyophorbe_lagenicaulis.jpg/320px-Hyophorbe_lagenicaulis.jpg',
  'Ziziphus mauritiana': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Jujube_-_Ziziphus_mauritiana.jpg/320px-Jujube_-_Ziziphus_mauritiana.jpg',
  'Galphimia glauca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Galphimia_glauca.jpg/320px-Galphimia_glauca.jpg',

  // ── SHRUBS ─────────────────────────────────────────────────────────────────
  'Bougainvillea glabra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Bougainvillea_glabra.jpg/320px-Bougainvillea_glabra.jpg',
  'Hibiscus rosa-sinensis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Hibiscus_rosa-sinensis_1.jpg/320px-Hibiscus_rosa-sinensis_1.jpg',
  'Lantana camara': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/LantanaCamara1.jpg/320px-LantanaCamara1.jpg',
  'Nerium oleander': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Nerium_oleander.jpg/320px-Nerium_oleander.jpg',
  'Ricinus communis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Ricinus_communis_003.JPG/320px-Ricinus_communis_003.JPG',
  'Calotropis gigantea': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Calotropis_gigantea_crown_flower_P1120023a.jpg/320px-Calotropis_gigantea_crown_flower_P1120023a.jpg',
  'Lawsonia inermis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Lawsonia_inermis.jpg/320px-Lawsonia_inermis.jpg',
  'Rosa indica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Rosa_indica.jpg/320px-Rosa_indica.jpg',
  'Duranta erecta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Duranta_erecta.jpg/320px-Duranta_erecta.jpg',
  'Tecoma stans': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Tecoma_stans.jpg/320px-Tecoma_stans.jpg',
  'Ixora coccinea': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Ixora_coccinea.jpg/320px-Ixora_coccinea.jpg',
  'Jasminum sambac': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Jasminum_sambac_%28L.%29_Aiton_%28Arabian_jasmine%29.jpg/320px-Jasminum_sambac_%28L.%29_Aiton_%28Arabian_jasmine%29.jpg',
  'Codiaeum variegatum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Codiaeum_variegatum.jpg/320px-Codiaeum_variegatum.jpg',
  'Barleria cristata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Barleria_cristata.jpg/320px-Barleria_cristata.jpg',
  'Carissa carandas': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Carissa_carandas.jpg/320px-Carissa_carandas.jpg',
  'Senna auriculata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Senna_auriculata.jpg/320px-Senna_auriculata.jpg',
  'Rubus ellipticus': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Rubus_ellipticus.jpg/320px-Rubus_ellipticus.jpg',
  'Capparis zeylanica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Capparis_zeylanica.jpg/320px-Capparis_zeylanica.jpg',
  'Grewia asiatica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Grewia_asiatica.jpg/320px-Grewia_asiatica.jpg',
  'Murraya paniculata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Murraya_paniculata.jpg/320px-Murraya_paniculata.jpg',
  'Thevetia peruviana': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Thevetia_peruviana.jpg/320px-Thevetia_peruviana.jpg',
  'Cestrum nocturnum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Cestrum_nocturnum.jpg/320px-Cestrum_nocturnum.jpg',
  'Clerodendrum inerme': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Clerodendrum_inerme.jpg/320px-Clerodendrum_inerme.jpg',
  'Plumbago zeylanica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Plumbago_zeylanica.jpg/320px-Plumbago_zeylanica.jpg',
  'Ipomoea cairica': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Ipomoea_cairica.jpg/320px-Ipomoea_cairica.jpg',
  'Abutilon indicum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Abutilon_indicum.jpg/320px-Abutilon_indicum.jpg',
  'Acalypha wilkesiana': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Acalypha_wilkesiana.jpg/320px-Acalypha_wilkesiana.jpg',
  'Achyranthes aspera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Achyranthes_aspera.jpg/320px-Achyranthes_aspera.jpg',
  'Annona reticulata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Annona_reticulata.jpg/320px-Annona_reticulata.jpg',
  'Jatropha gossypiifolia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Jatropha_gossypifolia.jpg/320px-Jatropha_gossypifolia.jpg',
  'Sesbania grandiflora': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Sesbania_grandiflora.jpg/320px-Sesbania_grandiflora.jpg',
  'Ruellia tuberosa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Ruellia_tuberosa.jpg/320px-Ruellia_tuberosa.jpg',
  'Ziziphus nummularia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Jujube_-_Ziziphus_mauritiana.jpg/320px-Jujube_-_Ziziphus_mauritiana.jpg',
  'Jasminum auriculatum': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Jasminum_sambac_%28L.%29_Aiton_%28Arabian_jasmine%29.jpg/320px-Jasminum_sambac_%28L.%29_Aiton_%28Arabian_jasmine%29.jpg',
};

/**
 * Get a Wikimedia Commons photo URL for a species by scientific name.
 * Falls back to null if not found (caller should use emoji fallback).
 * @param {string} scientificName
 * @returns {string|null}
 */
function getSpeciesImageUrl(scientificName) {
  if (!scientificName) return null;
  return SPECIES_IMAGES[scientificName.trim()] || null;
}
